export const quizData = {
  unit1: {
    name: "Unit 1: am/is/are - Present Tense of 'to be'",
    description: "Master the present tense of the verb 'to be' - am, is, and are",
    questions: [
      {
        question: "Which word completes the sentence? 'I _____ a student from Canada.'",
        options: ["am", "is", "are", "be"],
        correct: "0",
        explanation: "Use 'am' with the subject 'I'. The sentence means 'I am a student from Canada.'",
      },
      {
        question: "Choose the correct form: 'My sister _____ 25 years old.'",
        options: ["am", "is", "are", "being"],
        correct: "1",
        explanation: "Use 'is' with singular subjects like 'my sister'. She is 25 years old.",
      },
      {
        question: "Which sentence is correct?",
        options: [
          "They are not interested in sports.",
          "They is not interested in sports.",
          "They am not interested in sports.",
          "They be not interested in sports.",
        ],
        correct: "0",
        explanation: "Use 'are' with plural subjects like 'they'. They are not interested in sports.",
      },
      {
        question: "Complete: 'My parents _____ doctors.'",
        options: ["is", "am", "are", "been"],
        correct: "2",
        explanation: "Use 'are' with plural subjects 'my parents'. Both are doctors.",
      },
      {
        question: "Which is the negative form of 'I am happy'?",
        options: ["I'm not happy", "I amn't happy", "I'm not happy (I'm not = I am not)", "I are not happy"],
        correct: "0",
        explanation: "The negative form is 'I'm not happy' or 'I am not happy'.",
      },
      {
        question: "Choose the correct sentence:",
        options: [
          "It is a beautiful day today.",
          "It are a beautiful day today.",
          "It am a beautiful day today.",
          "It being a beautiful day today.",
        ],
        correct: "0",
        explanation: "Use 'is' with singular subjects like 'it'. It is a beautiful day today.",
      },
      {
        question: "What does this sentence mean? 'My favourite colour is blue.'",
        options: [
          "I like blue because it's my favorite",
          "Blue is the only color I like",
          "I own something that is blue",
          "Blue will become my favorite color",
        ],
        correct: "0",
        explanation: "This sentence identifies that blue is the speaker's favorite color.",
      },
      {
        question: "Complete: 'You _____ my best friend.'",
        options: ["am", "is", "are", "be"],
        correct: "2",
        explanation: "Use 'are' with the subject 'you'. You are my best friend.",
      },
      {
        question: "Which negative sentence is correct?",
        options: [
          "She's not a teacher.",
          "She isn't a teacher.",
          "She's not a teacher / She isn't a teacher (both correct)",
          "She ain't a teacher.",
        ],
        correct: "2",
        explanation: "Both 'is not' (isn't) and the contraction 'is not' (isn't) are correct.",
      },
      {
        question: "Complete: 'This bag _____ very heavy.'",
        options: ["are", "is", "am", "being"],
        correct: "1",
        explanation: "Use 'is' with the singular subject 'this bag'. This bag is very heavy.",
      },
      {
        question: "Choose the correct form: 'My brother and I _____ good tennis players.'",
        options: ["am", "is", "are", "be"],
        correct: "2",
        explanation: "Use 'are' with plural subjects. My brother and I are good tennis players.",
      },
      {
        question: "Which sentence is correct?",
        options: ["You am late for work.", "You is late for work.", "You are late for work.", "You be late for work."],
        correct: "2",
        explanation: "Use 'are' with 'you', whether singular or plural. You are late for work.",
      },
      {
        question: "Complete: 'Emily _____ at home. Her children _____ at school.'",
        options: ["is / are", "are / is", "am / are", "is / is"],
        correct: "0",
        explanation: "'Emily' (singular) takes 'is'. 'Children' (plural) takes 'are'.",
      },
      {
        question: "What is the contraction of 'he is'?",
        options: ["he'm", "he's", "he'is", "he-s"],
        correct: "1",
        explanation: "The contraction of 'he is' is 'he's'. Example: He's in bed.",
      },
      {
        question: "Choose the correct sentence:",
        options: ["We are good friends.", "We is good friends.", "We be good friends.", "We am good friends."],
        correct: "0",
        explanation: "Use 'are' with 'we'. We are good friends.",
      },
      {
        question: "Complete: 'Your keys _____ on the table.'",
        options: ["is", "am", "are", "be"],
        correct: "2",
        explanation: "Use 'are' with plural subjects. Your keys are on the table.",
      },
      {
        question: "Which sentence shows correct usage?",
        options: [
          "I'm cold, can you close the window?",
          "I'm cold, can you close the window? (Yes, this is correct)",
          "I am cold, can you close the window? (Yes, this is also correct)",
          "Both B and C are correct",
        ],
        correct: "3",
        explanation: "Both 'I'm' and 'I am' are correct. 'I'm' is the contraction.",
      },
      {
        question: "Complete: 'It _____ ten o'clock. You _____ late again.'",
        options: ["is / are", "are / is", "am / are", "is / is"],
        correct: "0",
        explanation: "'It' (singular) takes 'is'. 'You' takes 'are'.",
      },
      {
        question: "What does 'I'm not hungry' mean?",
        options: [
          "I will not be hungry",
          "I am not hungry (at this moment)",
          "I have never been hungry",
          "I might be hungry later",
        ],
        correct: "1",
        explanation: "'I'm not hungry' means you are not hungry right now.",
      },
      {
        question: "Choose the correct sentence:",
        options: [
          "These people are not English.",
          "These people is not English.",
          "These people am not English.",
          "These people be not English.",
        ],
        correct: "0",
        explanation: "Use 'are' with plural subjects. These people are not English.",
      },
    ],
  },
  unit2: {
    name: "Unit 2: Questions with am/is/are",
    description: "Learn how to form and answer questions using am, is, and are",
    questions: [
      {
        question: "Which is the correct question form?",
        options: ["Is he a doctor?", "Is a doctor he?", "A doctor is he?", "He is a doctor?"],
        correct: "0",
        explanation: "In questions, the verb comes before the subject: 'Is he a doctor?'",
      },
      {
        question: "How do you ask about someone's name?",
        options: ["Name is what yours?", "What is your name?", "Your name what is?", "Is what your name?"],
        correct: "1",
        explanation: "The correct question form is 'What is your name?'",
      },
      {
        question: "What is the correct question?",
        options: ["Are you married?", "You are married?", "Married you are?", "Are married you?"],
        correct: "0",
        explanation: "In questions, verb comes first: 'Are you married?'",
      },
      {
        question: "Complete the question: 'How old _____ you?'",
        options: ["am", "is", "are", "be"],
        correct: "2",
        explanation: "Use 'are' with 'you': 'How old are you?'",
      },
      {
        question: "What is the correct question form?",
        options: [
          "Where is your mother?",
          "Where your mother is?",
          "Is where your mother?",
          "Where is at your mother?",
        ],
        correct: "0",
        explanation: "Correct question order: 'Where is your mother?'",
      },
      {
        question: "How would you ask if someone is a student?",
        options: ["Student are you?", "You are a student?", "Are you a student?", "A student you are?"],
        correct: "2",
        explanation: "The correct question is 'Are you a student?'",
      },
      {
        question: "Complete: 'Is she _____ home?'",
        options: ["at", "on", "in", "to"],
        correct: "0",
        explanation: "We use 'at' with 'home': 'Is she at home?'",
      },
      {
        question: "What is the correct negative response to 'Are you tired?'",
        options: ["Yes, I am.", "No, I'm not.", "No, I am not tired.", "Both B and C are correct"],
        correct: "3",
        explanation: "Both 'No, I'm not.' and 'No, I am not tired.' are correct.",
      },
      {
        question: "How do you ask about the weather?",
        options: ["Is cold it today?", "Cold is it today?", "Is it cold today?", "It is cold today?"],
        correct: "2",
        explanation: "The correct question is 'Is it cold today?'",
      },
      {
        question: "Complete: 'Are your parents _____ home?'",
        options: ["on", "at", "in", "to"],
        correct: "1",
        explanation: "We use 'at' with 'home': 'Are your parents at home?'",
      },
      {
        question: "What is the short answer to 'Is your friend English?'",
        options: ["Yes, she is.", "Yes, is.", "Yes, friend is.", "Is English."],
        correct: "0",
        explanation: "The correct short answer is 'Yes, she is.' (or 'Yes, he is.')",
      },
      {
        question: "Which question is correct?",
        options: [
          "What colour is your car?",
          "What is colour your car?",
          "Is what colour your car?",
          "Colour what is your car?",
        ],
        correct: "0",
        explanation: "Correct question: 'What colour is your car?'",
      },
      {
        question: "Complete: '_____ you from Canada?'",
        options: ["Is", "Are", "Am", "Be"],
        correct: "1",
        explanation: "Use 'are' with 'you': 'Are you from Canada?'",
      },
      {
        question: "How do you ask about someone's age?",
        options: ["How old are you?", "How you are old?", "Old how are you?", "Are you how old?"],
        correct: "0",
        explanation: "The correct question is 'How old are you?'",
      },
      {
        question: "What is the short answer to 'Are these your keys?'",
        options: ["Yes, they are.", "Yes, keys are.", "Yes, these are.", "Yes, are."],
        correct: "0",
        explanation: "The correct short answer is 'Yes, they are.'",
      },
      {
        question: "Complete: 'Is she _____ the office?'",
        options: ["at", "on", "in", "to"],
        correct: "2",
        explanation: "We use 'in' for 'the office': 'Is she in the office?'",
      },
      {
        question: "Which is the correct response to 'Is it hot outside?'",
        options: ["No, it isn't.", "No, it's not.", "Both A and B are correct", "No, outside it isn't."],
        correct: "2",
        explanation: "'No, it isn't.' and 'No, it's not.' are both correct.",
      },
      {
        question: "What is the correct question?",
        options: [
          "Why is it so expensive?",
          "Why so expensive is it?",
          "Is expensive why it?",
          "Why it is so expensive?",
        ],
        correct: "0",
        explanation: "Correct question: 'Why is it so expensive?'",
      },
      {
        question: "Complete: '_____ are your shoes new?'",
        options: ["Is", "Are", "Am", "Be"],
        correct: "1",
        explanation: "Use 'are' with the plural subject 'shoes': 'Are your shoes new?'",
      },
      {
        question: "How would you confirm if someone is a teacher?",
        options: ["You are a teacher?", "Is a teacher you?", "Are you a teacher?", "A teacher is you?"],
        correct: "2",
        explanation: "The correct question is 'Are you a teacher?'",
      },
    ],
  },
  unit3: {
    name: "Unit 3: Present Continuous (is/are + -ing)",
    description: "Master the present continuous tense for actions happening right now",
    questions: [
      {
        question: "Which sentence uses present continuous correctly?",
        options: ["She is eat an apple.", "She is eating an apple.", "She eating is an apple.", "She is eating apple."],
        correct: "1",
        explanation: "Present continuous is 'is/are + -ing form'. She is eating an apple (action in progress).",
      },
      {
        question: "Complete: 'They _____ playing football right now.'",
        options: ["is", "am", "are", "be"],
        correct: "2",
        explanation: "Use 'are' with plural subject 'they': They are playing football.",
      },
      {
        question: "What does present continuous describe?",
        options: [
          "Actions that happened in the past",
          "Actions that will happen in the future",
          "Actions that are happening right now",
          "Actions that happen every day",
        ],
        correct: "2",
        explanation: "Present continuous describes actions happening at this very moment.",
      },
      {
        question: "Choose the correct present continuous form:",
        options: [
          "He is work in the garden.",
          "He is working in the garden.",
          "He working is in the garden.",
          "He is work garden.",
        ],
        correct: "1",
        explanation: "Correct form: 'He is working in the garden.'",
      },
      {
        question: "What is the negative form of 'I'm working'?",
        options: ["I'm not working", "I not working", "I'm not work", "I not am working"],
        correct: "0",
        explanation: "The negative is 'I'm not working' or 'I am not working'.",
      },
      {
        question: "Complete: 'Maria _____ a newspaper.'",
        options: ["is read", "is reading", "reading is", "are reading"],
        correct: "1",
        explanation: "Correct form: 'Maria is reading a newspaper.'",
      },
      {
        question: "How do you form the -ing form of 'run'?",
        options: ["runing", "running", "rune", "run"],
        correct: "1",
        explanation: "Double the final consonant: run → running. They are running in the park.",
      },
      {
        question: "Which sentence is in present continuous?",
        options: ["She wears a hat.", "She is wearing a hat.", "She wore a hat.", "She will wear a hat."],
        correct: "1",
        explanation: "'She is wearing a hat' is present continuous (action happening now).",
      },
      {
        question: "Complete: 'We _____ not watching TV right now.'",
        options: ["am", "is", "are", "be"],
        correct: "2",
        explanation: "Use 'are' with 'we': 'We are not watching TV right now.'",
      },
      {
        question: "What is the present continuous of 'sit'?",
        options: ["siting", "sitting", "sitted", "sit"],
        correct: "1",
        explanation: "Double the final consonant: sit → sitting. She is sitting on the chair.",
      },
      {
        question: "Choose the correct form:",
        options: [
          "You're not listening to me.",
          "You're not listen to me.",
          "You not listening to me.",
          "You're listening to me.",
        ],
        correct: "0",
        explanation: "Correct: 'You're not listening to me.' (You are not listening)",
      },
      {
        question: "What is happening in the sentence 'The bus is coming'?",
        options: [
          "The bus came in the past.",
          "The bus will come in the future.",
          "The bus is arriving right now.",
          "The bus comes every day.",
        ],
        correct: "2",
        explanation: "'The bus is coming' means the bus is arriving at this moment.",
      },
      {
        question: "Complete: 'Look! There _____ Chris. He _____ dancing.'",
        options: ["is / is", "are / are", "is / is dancing (he's dancing)", "are / are dancing"],
        correct: "2",
        explanation: "'Look! There's Chris. He's dancing!' (present continuous of what's happening now)",
      },
      {
        question: "How do you ask if someone is doing something in present continuous?",
        options: ["You working?", "Are you work?", "Are you working?", "You are work?"],
        correct: "2",
        explanation: "Correct question: 'Are you working?' (present continuous question form)",
      },
      {
        question: "What does 'I'm not working' mean?",
        options: [
          "I don't have a job",
          "I am not doing work right now",
          "I will never work",
          "I didn't work yesterday",
        ],
        correct: "1",
        explanation: "'I'm not working' means I am not working at this specific moment.",
      },
      {
        question: "Complete: 'She _____ wearing a hat.'",
        options: ["am", "is", "are", "be"],
        correct: "1",
        explanation: "Use 'is' with singular 'she': 'She is wearing a hat.'",
      },
      {
        question: "Choose the correct response to 'What are they doing?'",
        options: [
          "They play football.",
          "They are playing football.",
          "They playing football.",
          "They are play football.",
        ],
        correct: "1",
        explanation: "Correct answer: 'They are playing football.' (present continuous)",
      },
      {
        question: "What is the present continuous form of 'write'?",
        options: ["writeing", "writting", "writing", "write"],
        correct: "2",
        explanation: "Drop the 'e' and add '-ing': write → writing. She is writing a letter.",
      },
      {
        question: "Complete: 'We're having dinner now. Can I call you later?'",
        options: ["We eat dinner now.", "We are having dinner now.", "We have dinner now.", "We will have dinner now."],
        correct: "1",
        explanation: "'We're having dinner' (present continuous) describes the action happening right now.",
      },
      {
        question: "What does 'The weather is nice. It's not raining' mean?",
        options: [
          "It rained in the past and will rain in the future.",
          "It is sunny and no rain is falling at this moment.",
          "It never rains in this place.",
          "The weather will be nice tomorrow.",
        ],
        correct: "1",
        explanation: "'It's not raining' (present continuous negative) means rain is not happening now.",
      },
    ],
  },
}
